[tool.poetry]
name = "perfcat"
version = "0.1.0"
description = ""
authors = ["dengxuan <303359166@qq.com>"]

[tool.poetry.dependencies]
python = ">=3.6.2,<3.11"
pyside6 = "^6.3.0"
pywin32 = {version="^303", markers="sys_platform == 'win32'"}
pywin32-stubs = {version="^0.1.4", markers="sys_platform == 'win32'"}
icespringpysidestubs-pyside6 = "^1.3.1"
markdown = "^3.3.6"
importlib = "^1.0.4"
importlib-metadata = {version = "^1.0", python = "<3.8"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
